CREATE DATABASE IF NOT EXISTS auction_auth_service;
USE auction_auth_service;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  role VARCHAR(20) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS credentials (
  id INT AUTO_INCREMENT PRIMARY KEY,
  site VARCHAR(50) NOT NULL,
  account_name VARCHAR(50) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ui_restrictions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL,
  selector TEXT NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INITIAL DATA - REPLACE THESE WITH REAL VALUES IN YOUR DATABASE
-- DO NOT COMMIT THIS FILE WITH REAL CREDENTIALS IF YOU USE THEM HERE

-- INSERT INTO users (username, role) VALUES ('usalogistics', 'logistics');

-- INSERT INTO credentials (site, account_name, username, password) VALUES 
-- ('copart', 'copart1', 'YOUR_COPART_USERNAME', 'YOUR_COPART_PASSWORD'),
-- ('copart', 'copart2', 'YOUR_COPART_USERNAME_2', 'YOUR_COPART_PASSWORD_2'),
-- ('iaai', 'iaai', 'YOUR_IAAI_USERNAME', 'YOUR_IAAI_PASSWORD');
